MAX_LENGTH_NAME = 124
MAX_LENGTH_SURNAME = 124
MAX_LENGTH_PHONE = 12
MAX_LENGTH_ABOUT = 256
MAX_LENGTH_SKILL_NAME = 124
MAX_LENGTH_PROJECT_NAME = 200

STATUS_OPEN = 'open'
STATUS_CLOSED = 'closed'
STATUS_CHOICES = [
    (STATUS_OPEN, 'Открыт'),
    (STATUS_CLOSED, 'Закрыт'),
]

PAGINATION_PAGE_SIZE = 12
SKILL_AUTOCOMPLETE_LIMIT = 10

AVATAR_COLOR_RED = '#FF6B6B'
AVATAR_COLOR_TEAL = '#4ECDC4'
AVATAR_COLOR_BLUE = '#45B7D1'
AVATAR_COLOR_GREEN = '#96CEB4'
AVATAR_COLOR_YELLOW = '#FFEAA7'
AVATAR_COLOR_PURPLE = '#DDA0DD'

AVATAR_COLORS = [
    AVATAR_COLOR_RED,
    AVATAR_COLOR_TEAL,
    AVATAR_COLOR_BLUE,
    AVATAR_COLOR_GREEN,
    AVATAR_COLOR_YELLOW,
    AVATAR_COLOR_PURPLE,
]

AVATAR_SIZE = 200
AVATAR_TEXT_COLOR = 'white'
FONT_SIZE = 100
